package com.shuffle.scplayer.jna;
import com.sun.jna.Callback;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SpConnectionCallbacks extends Structure {
	/** C type : notify_callback* */
	public SpPlaybackCallbacks.notify_callback notify$;
	/** C type : new_credentials_callback* */
	public SpConnectionCallbacks.new_credentials_callback new_credentials;
	public interface notify_callback extends Callback {
		void apply(int notification, Pointer userdata);
	};
	public interface new_credentials_callback extends Callback {
		void apply(Pointer blob, Pointer userdata);
	};
	public SpConnectionCallbacks() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("notify$", "new_credentials");
	}
	/**
	 * @param notify$ C type : notify_callback*<br>
	 * @param new_credentials C type : new_credentials_callback*
	 */
	public SpConnectionCallbacks(SpPlaybackCallbacks.notify_callback notify$, SpConnectionCallbacks.new_credentials_callback new_credentials) {
		super();
		this.notify$ = notify$;
		this.new_credentials = new_credentials;
	}
	public SpConnectionCallbacks(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends SpConnectionCallbacks implements Structure.ByReference {
		
	};
	public static class ByValue extends SpConnectionCallbacks implements Structure.ByValue {
		
	};
}
