package com.shuffle.scplayer.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SpMetadata extends Structure {
	/** C type : char[0x100] */
	public byte[] data0 = new byte[0x100];
	/** C type : char[0x80] */
	public byte[] context_uri = new byte[0x80];
	/** C type : char[0x100] */
	public byte[] track_name = new byte[0x100];
	/** C type : char[0x80] */
	public byte[] track_uri = new byte[0x80];
	/** C type : char[0x100] */
	public byte[] artist_name = new byte[0x100];
	/** C type : char[0x80] */
	public byte[] artist_uri = new byte[0x80];
	/** C type : char[0x100] */
	public byte[] album_name = new byte[0x100];
	/** C type : char[0x80] */
	public byte[] album_uri = new byte[0x80];
	/** C type : char[0x80] */
	public byte[] cover_uri = new byte[0x80];
	public int duration;
	public SpMetadata() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("data0", "context_uri", "track_name", "track_uri", "artist_name", "artist_uri", "album_name", "album_uri", "cover_uri", "duration");
	}
	public SpMetadata(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends SpMetadata implements Structure.ByReference {
		
	};
	public static class ByValue extends SpMetadata implements Structure.ByValue {
		
	};
}
